// Generated by scripts/sync-web-assets.mjs from the website. Do not edit directly.
(function () {
/** Consume SSE over POST, preserving UTF-8 characters and split event frames. */
async function readEventStream(response, { onSnapshot = () => {}, onProgress = () => {}, onDone }, subject = "explanation") {
  if (!response.ok) {
    const data = await response.json().catch(() => ({}));
    throw Object.assign(new Error(data.message || `The ${subject} could not be loaded. Try again.`), { code: data.error_code });
  }
  // Allows the new UI to work while an older API process is being restarted.
  if (!response.headers.get("content-type")?.includes("text/event-stream")) {
    onDone(await response.json());
    return;
  }
  if (!response.body) throw new Error("Streaming is unavailable. Please try again.");
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let completed = false;
  function consume(frame) {
    const lines = frame.split(/\r?\n/);
    const event = lines.find((line) => line.startsWith("event:"))?.slice(6).trim();
    const payload = lines.filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()).join("\n");
    if (!payload) return;
    const data = JSON.parse(payload);
    if (event === "error") throw Object.assign(new Error(data.message || `The ${subject} was interrupted. Try again.`), { code: data.error_code });
    if (event === "snapshot") onSnapshot(data);
    if (event === "progress") onProgress(data);
    if (event === "done") { completed = true; onDone(data); }
  }
  try {
    while (!completed) {
      const { value, done } = await reader.read();
      buffer += decoder.decode(value, { stream: !done });
      if (buffer.length > 128000) throw new Error(`The ${subject} response is too large.`);
      const frames = buffer.split(/\r?\n\r?\n/);
      buffer = frames.pop();
      for (const frame of frames) {
        consume(frame);
        if (completed) break;
      }
      if (done) {
        if (buffer.trim() && !completed) consume(buffer);
        break;
      }
    }
    if (!completed) throw new Error(`The ${subject} was interrupted. Please try again.`);
  } finally {
    await reader.cancel().catch(() => {});
    reader.releaseLock();
  }
}

const readExplanationStream = (response, handlers) => readEventStream(response, handlers, "explanation");
const readScanStream = (response, handlers) => readEventStream(response, handlers, "scan");

Object.assign(self.Phisang ||= {}, { readEventStream, readExplanationStream, readScanStream });
})();
