// Generated by scripts/sync-web-assets.mjs from the website. Do not edit directly.
(function () {
const CLASS_META = {
  malware: { bananaState: "rotten", verdict: "High risk", hint: "This address appears in a threat database. Avoid opening it or downloading files.", tone: "text-bruise", dot: "bg-bruise", rots: true },
  phishing: { bananaState: "rotten", verdict: "High risk", hint: "The scan found signs associated with phishing. Avoid sharing passwords or payment details.", tone: "text-rot", dot: "pat-speckle" },
  benign: { bananaState: "benign", verdict: "No clear warning", hint: "These checks found no clear threat. This is not a guarantee of safety.", tone: "text-forest", dot: "bg-peel" },
  unavailable: { bananaState: "unavailable", verdict: "Couldn’t check this site", hint: "A required check could not finish, so the risk is unknown. Try scanning again later.", tone: "text-leaf", dot: "pat-hatch" },
  checking: { bananaState: "checking", verdict: "Checking the link", hint: "Checking for known threats and gathering information about the website.", tone: "text-leaf", dot: "bg-leaf" },
};

// Score bands for the risk percentage, mirroring the cuts in backend/app/risk.py.
// Colour never signals alone: every band also shows its word next to the number.
const RISK_BANDS = [
  { from: 0.8, key: "very-high", label: "Very high", tone: "text-risk-very-high", fill: "bg-risk-very-high" },
  { from: 0.6, key: "high", label: "High", tone: "text-risk-high", fill: "bg-risk-high" },
  { from: 0.4, key: "medium", label: "Medium", tone: "text-risk-medium", fill: "bg-risk-medium" },
  { from: 0, key: "low", label: "Low", tone: "text-risk-low", fill: "bg-risk-low" },
];

function riskBand(score) {
  return RISK_BANDS.find(band => score >= band.from) || RISK_BANDS[RISK_BANDS.length - 1];
}

// Shared with the extension: the displayed high-risk verdict is also its stop rule.
function isHighRisk(result, cls = result?.classification) {
  if (!result || cls === "unavailable") return false;
  return cls === "malware" || cls === "phishing" || result.verdict === "malicious"
    || (result.risk_score ?? 0) >= 0.6;
}

function verdictMeta(result, cls) {
  const base = CLASS_META[cls] || CLASS_META.unavailable;
  if (!result || cls === "unavailable" || cls === "malware") return base;
  if (isHighRisk(result, cls)) {
    return { ...CLASS_META.phishing, hint: cls === "benign"
      ? "The page model flagged this site, while other checks found less evidence. Be cautious and avoid sharing sensitive details."
      : CLASS_META.phishing.hint };
  }
  if (result.verdict === "potentially_unsafe" || (result.risk_score ?? 0) >= 0.4) {
    return { ...base, verdict: "Be cautious", bananaState: "phishing", tone: "text-rot", dot: "pat-speckle",
      hint: result.prior?.ever_malicious ? "An earlier scan flagged this address. Verify it independently before sharing any details."
        : "The checks found mixed signals. Verify the website before sharing personal details." };
  }
  return base;
}

Object.assign(self.Phisang ||= {}, { CLASS_META, RISK_BANDS, riskBand, verdictMeta, isHighRisk });
})();
